### ISSUE TITLE
Update docs to install crypto library

### ISSUE THREAD

**Issue by chrxr** [tomdyson/wagalytics#1]
Hi  @tomdyson, 

this looks great, just working through the install now. First issue I've come across is that it requires a crypto library to be installed. I used PyOpenSSl locally. Could this be added to the docs?

Cheers,
Chris

**Comment by tomdyson** [comment]
Thanks @chrxr! That's odd - I thought the relevant crypto stuff was included in one of google-api-python-client or oauth2client. Did one of those complain about lacking crypto?

**Comment by chrxr** [comment]
Yep, error below:

    Internal Server Error: /admin/analytics/dashboard/
    Traceback (most recent call last):
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
        response = viewfunc(request, *args, **kw)
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/wagalytics/views.py", line 27, in dashboard
        'access_token': get_access_token(settings.GA_KEY_FILEPATH),
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/wagalytics/views.py", line 21, in get_access_token
        _key_data['client_email'], _key_data['private_key'], SCOPE)
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/oauth2client/util.py", line 140, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/oauth2client/client.py", line 1630, in __init__
        _RequireCryptoOrDie()
      File "/Users/chrisrogers/blog_project/lib/python2.7/site-packages/oauth2client/client.py", line 1581, in _RequireCryptoOrDie
        raise CryptoUnavailableError('No crypto library available')
    CryptoUnavailableError: No crypto library available

**Comment by tomdyson** [comment]
Thanks. I found this:

http://stackoverflow.com/questions/27305867/google-api-access-using-service-account-oauth2client-client-cryptounavailableerr

Did you fix it with PyOpenSSl via pip?

**Comment by chrxr** [comment]
I did indeed, from that exact answer :)

**Comment by tomdyson** [comment]
Thanks! I've updated the docs. Were the other steps clear enough?

**Comment by chrxr** [comment]
Everything seems to install correctly, but I'm having a little trouble with JS errors. I'm investigating and will post a separate issue if necessary.

Cheers!
