### ISSUE TITLE
Internal Server Error: /admin/analytics/dashboard/, KeyError: 'staticfiles'

### ISSUE THREAD

**Issue by alexgleason** [tomdyson/wagalytics#48]
After upgrading to the latest Wagtail version:

```
2020-06-04T14:51:00.030219+00:00 app[web.1]: Internal Server Error: /admin/analytics/dashboard/

2020-06-04T14:51:00.030237+00:00 app[web.1]: Traceback (most recent call last):

2020-06-04T14:51:00.030241+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 1021, in find_library

2020-06-04T14:51:00.030241+00:00 app[web.1]:     return parser.libraries[name]

2020-06-04T14:51:00.030242+00:00 app[web.1]: KeyError: 'staticfiles'

2020-06-04T14:51:00.030243+00:00 app[web.1]: 

2020-06-04T14:51:00.030243+00:00 app[web.1]: During handling of the above exception, another exception occurred:

2020-06-04T14:51:00.030244+00:00 app[web.1]: 

2020-06-04T14:51:00.030244+00:00 app[web.1]: Traceback (most recent call last):

2020-06-04T14:51:00.030245+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner

2020-06-04T14:51:00.030245+00:00 app[web.1]:     response = get_response(request)

2020-06-04T14:51:00.030246+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response

2020-06-04T14:51:00.030246+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)

2020-06-04T14:51:00.030247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response

2020-06-04T14:51:00.030247+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)

2020-06-04T14:51:00.030247+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func

2020-06-04T14:51:00.030248+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)

2020-06-04T14:51:00.030248+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/admin/urls/__init__.py", line 109, in wrapper

2020-06-04T14:51:00.030249+00:00 app[web.1]:     return view_func(request, *args, **kwargs)

2020-06-04T14:51:00.030249+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagtail/admin/auth.py", line 168, in decorated_view

2020-06-04T14:51:00.030249+00:00 app[web.1]:     response = view_func(request, *args, **kwargs)

2020-06-04T14:51:00.030250+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/wagalytics/views.py", line 57, in dashboard

2020-06-04T14:51:00.030250+00:00 app[web.1]:     'initial_start_date': initial_start_date,

2020-06-04T14:51:00.030251+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render

2020-06-04T14:51:00.030251+00:00 app[web.1]:     content = loader.render_to_string(template_name, context, request, using=using)

2020-06-04T14:51:00.030251+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader.py", line 61, in render_to_string

2020-06-04T14:51:00.030252+00:00 app[web.1]:     template = get_template(template_name, using=using)

2020-06-04T14:51:00.030252+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader.py", line 15, in get_template

2020-06-04T14:51:00.030253+00:00 app[web.1]:     return engine.get_template(template_name)

2020-06-04T14:51:00.030253+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/backends/django.py", line 34, in get_template

2020-06-04T14:51:00.030254+00:00 app[web.1]:     return Template(self.engine.get_template(template_name), self)

2020-06-04T14:51:00.030254+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/engine.py", line 143, in get_template

2020-06-04T14:51:00.030254+00:00 app[web.1]:     template, origin = self.find_template(template_name)

2020-06-04T14:51:00.030255+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/engine.py", line 125, in find_template

2020-06-04T14:51:00.030255+00:00 app[web.1]:     template = loader.get_template(name, skip=skip)

2020-06-04T14:51:00.030255+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loaders/cached.py", line 53, in get_template

2020-06-04T14:51:00.030256+00:00 app[web.1]:     template = super().get_template(template_name, skip)

2020-06-04T14:51:00.030256+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loaders/base.py", line 30, in get_template

2020-06-04T14:51:00.030257+00:00 app[web.1]:     contents, origin, origin.template_name, self.engine,

2020-06-04T14:51:00.030257+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 156, in __init__

2020-06-04T14:51:00.030257+00:00 app[web.1]:     self.nodelist = self.compile_nodelist()

2020-06-04T14:51:00.030258+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 194, in compile_nodelist

2020-06-04T14:51:00.030258+00:00 app[web.1]:     return parser.parse()

2020-06-04T14:51:00.030259+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 477, in parse

2020-06-04T14:51:00.030259+00:00 app[web.1]:     raise self.error(token, e)

2020-06-04T14:51:00.030259+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 475, in parse

2020-06-04T14:51:00.030260+00:00 app[web.1]:     compiled_result = compile_func(self, token)

2020-06-04T14:51:00.030260+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/loader_tags.py", line 266, in do_extends

2020-06-04T14:51:00.030261+00:00 app[web.1]:     nodelist = parser.parse()

2020-06-04T14:51:00.030261+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 477, in parse

2020-06-04T14:51:00.030261+00:00 app[web.1]:     raise self.error(token, e)

2020-06-04T14:51:00.030262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/base.py", line 475, in parse

2020-06-04T14:51:00.030262+00:00 app[web.1]:     compiled_result = compile_func(self, token)

2020-06-04T14:51:00.030262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 1078, in load

2020-06-04T14:51:00.030263+00:00 app[web.1]:     lib = find_library(parser, name)

2020-06-04T14:51:00.030272+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/template/defaulttags.py", line 1025, in find_library

2020-06-04T14:51:00.030272+00:00 app[web.1]:     name, "\n".join(sorted(parser.libraries)),

2020-06-04T14:51:00.030273+00:00 app[web.1]: django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:

2020-06-04T14:51:00.030273+00:00 app[web.1]: admin_list

2020-06-04T14:51:00.030273+00:00 app[web.1]: admin_modify

2020-06-04T14:51:00.030274+00:00 app[web.1]: admin_urls

2020-06-04T14:51:00.030274+00:00 app[web.1]: cache

2020-06-04T14:51:00.030274+00:00 app[web.1]: compress

2020-06-04T14:51:00.030275+00:00 app[web.1]: homepage_tags

2020-06-04T14:51:00.030275+00:00 app[web.1]: i18n

2020-06-04T14:51:00.030275+00:00 app[web.1]: l10n

2020-06-04T14:51:00.030276+00:00 app[web.1]: log

2020-06-04T14:51:00.030276+00:00 app[web.1]: modeladmin_tags

2020-06-04T14:51:00.030276+00:00 app[web.1]: navigation_tags

2020-06-04T14:51:00.030277+00:00 app[web.1]: news_tags

2020-06-04T14:51:00.030277+00:00 app[web.1]: people_tags

2020-06-04T14:51:00.030277+00:00 app[web.1]: projecttier_tags

2020-06-04T14:51:00.030278+00:00 app[web.1]: static

2020-06-04T14:51:00.030278+00:00 app[web.1]: tz

2020-06-04T14:51:00.030278+00:00 app[web.1]: wagtailadmin_tags

2020-06-04T14:51:00.030279+00:00 app[web.1]: wagtailcore_tags

2020-06-04T14:51:00.030279+00:00 app[web.1]: wagtailembeds_tags

2020-06-04T14:51:00.030279+00:00 app[web.1]: wagtailfontawesome

2020-06-04T14:51:00.030280+00:00 app[web.1]: wagtailimages_tags

2020-06-04T14:51:00.030280+00:00 app[web.1]: wagtailui_tags

2020-06-04T14:51:00.030280+00:00 app[web.1]: wagtailuserbar

2020-06-04T14:51:00.030281+00:00 app[web.1]: wagtailusers_tags
```

**Comment by alexgleason** [comment]
False alarm, this is fixed by the latest version! :smiley:
